on:
  push:
    branches:
      - main

concurrency: ci-${{ github.workflow }}-${{ github.ref }}

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  call-release-workflow:
    uses: JamieTaffurelliOrg/github-actions-templates/.github/workflows/release-template.yaml@main
    secrets: inherit
