on: pull_request

concurrency: ci-${{ github.workflow }}-${{ github.ref }}

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  call-terraform-docs-workflow:
    uses: JamieTaffurelliOrg/github-actions-templates/.github/workflows/terraform-docs-template.yaml@main
    secrets: inherit
